/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voip_v2;

import java.awt.Color;

/**
 *
 * @author edgar
 */
public class UI extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form UI
     */
    public UI() {
        
    }
    
    public void start(){
        Thread thread = new Thread(this);
	thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Socket1StartSend = new javax.swing.JButton();
        Socket2StartSend = new javax.swing.JButton();
        Socket3StartSend = new javax.swing.JButton();
        Socket4StartSend = new javax.swing.JButton();
        Socket1StopSend = new javax.swing.JButton();
        Socket2StopSend = new javax.swing.JButton();
        Socket3StopSend = new javax.swing.JButton();
        Socket4StopSend = new javax.swing.JButton();
        Socket1StartReceive = new javax.swing.JButton();
        Socket2StartReceive = new javax.swing.JButton();
        Socket3StartReceive = new javax.swing.JButton();
        Socket4StartReceive = new javax.swing.JButton();
        Socket1StopReceive = new javax.swing.JButton();
        Socket2StopReceive = new javax.swing.JButton();
        Socket3StopReceive = new javax.swing.JButton();
        Socket4StopReceive = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        iPAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        log = new javax.swing.JTextField();
        log2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DatagramSocket1:");

        jLabel2.setText("DatagramSocket2:");

        jLabel3.setText("DatagramSocket3:");

        jLabel4.setText("DatagramSocket4:");

        Socket1StartSend.setText("Start Send");
        Socket1StartSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket1StartSendActionPerformed(evt);
            }
        });

        Socket2StartSend.setText("Start Send");
        Socket2StartSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket2StartSendActionPerformed(evt);
            }
        });

        Socket3StartSend.setText("Start Send");
        Socket3StartSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket3StartSendActionPerformed(evt);
            }
        });

        Socket4StartSend.setText("Start Send");
        Socket4StartSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket4StartSendActionPerformed(evt);
            }
        });

        Socket1StopSend.setEnabled(false);
        Socket1StopSend.setText("Stop Send");
        Socket1StopSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket1StopSendActionPerformed(evt);
            }
        });

        Socket2StopSend.setEnabled(false);
        Socket2StopSend.setText("Stop Send");
        Socket2StopSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket2StopSendActionPerformed(evt);
            }
        });

        Socket3StopSend.setEnabled(false);
        Socket3StopSend.setText("Stop Send");
        Socket3StopSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket3StopSendActionPerformed(evt);
            }
        });

        Socket4StopSend.setEnabled(false);
        Socket4StopSend.setText("Stop Send");
        Socket4StopSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket4StopSendActionPerformed(evt);
            }
        });

        Socket1StartReceive.setText("Start Receive");
        Socket1StartReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket1StartReceiveActionPerformed(evt);
            }
        });

        Socket2StartReceive.setText("Start Receive");
        Socket2StartReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket2StartReceiveActionPerformed(evt);
            }
        });

        Socket3StartReceive.setText("Start Receive");
        Socket3StartReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket3StartReceiveActionPerformed(evt);
            }
        });

        Socket4StartReceive.setText("Start Receive");
        Socket4StartReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket4StartReceiveActionPerformed(evt);
            }
        });

        Socket1StopReceive.setEnabled(false);
        Socket1StopReceive.setText("Stop Receive");
        Socket1StopReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket1StopReceiveActionPerformed(evt);
            }
        });

        Socket2StopReceive.setEnabled(false);
        Socket2StopReceive.setText("Stop Receive");
        Socket2StopReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket2StopReceiveActionPerformed(evt);
            }
        });

        Socket3StopReceive.setEnabled(false);
        Socket3StopReceive.setText("Stop Receive");
        Socket3StopReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket3StopReceiveActionPerformed(evt);
            }
        });

        Socket4StopReceive.setEnabled(false);
        Socket4StopReceive.setText("Stop Receive");
        Socket4StopReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Socket4StopReceiveActionPerformed(evt);
            }
        });

        jLabel5.setText("IP Address:");

        iPAddress.setText("localhost");
        GlobalVariables.iPAddress = iPAddress.getText();
        iPAddress.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                iPAddressCaretUpdate(evt);
            }
        });

        jLabel6.setText("Port:");

        port.setText("55555");
        GlobalVariables.port = Integer.parseInt(port.getText());
        port.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                portCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(log2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Socket4StartSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket4StopSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket4StartReceive)
                                .addGap(18, 18, 18)
                                .addComponent(Socket4StopReceive))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Socket3StartSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket3StopSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket3StartReceive)
                                .addGap(18, 18, 18)
                                .addComponent(Socket3StopReceive))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Socket2StartSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket2StopSend)
                                .addGap(18, 18, 18)
                                .addComponent(Socket2StartReceive)
                                .addGap(18, 18, 18)
                                .addComponent(Socket2StopReceive))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(iPAddress)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Socket1StartSend)
                                        .addGap(18, 18, 18)
                                        .addComponent(Socket1StopSend)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Socket1StartReceive)
                                        .addGap(18, 18, 18)
                                        .addComponent(Socket1StopReceive))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(iPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Socket1StartSend)
                    .addComponent(Socket1StopSend)
                    .addComponent(Socket1StartReceive)
                    .addComponent(Socket1StopReceive))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Socket2StartSend)
                    .addComponent(Socket2StopSend)
                    .addComponent(Socket2StartReceive)
                    .addComponent(Socket2StopReceive))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Socket3StartSend)
                    .addComponent(Socket3StopSend)
                    .addComponent(Socket3StartReceive)
                    .addComponent(Socket3StopReceive))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Socket4StartSend)
                    .addComponent(Socket4StopSend)
                    .addComponent(Socket4StartReceive)
                    .addComponent(Socket4StopReceive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(log2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Socket2StartSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket2StartSendActionPerformed
        Socket1StartSend.setEnabled(false);
        Socket2StartSend.setEnabled(false);
        Socket3StartSend.setEnabled(false);
        Socket4StartSend.setEnabled(false);
        Socket2StopSend.setEnabled(true);
        
        GlobalVariables.Socket2SendRun = true;
        Socket2Sender socket2Sender = new Socket2Sender();
        socket2Sender.start();
        
        
        
    }//GEN-LAST:event_Socket2StartSendActionPerformed

    private void Socket2StopSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket2StopSendActionPerformed
        Socket1StartSend.setEnabled(true);
        Socket2StartSend.setEnabled(true);
        Socket3StartSend.setEnabled(true);
        Socket4StartSend.setEnabled(true);
        Socket2StopSend.setEnabled(false);
        Socket1StartReceive.setEnabled(true);
        Socket2StartReceive.setEnabled(true);
        Socket3StartReceive.setEnabled(true);
        Socket4StartReceive.setEnabled(true);
        GlobalVariables.Socket2SendRun = false;
        
        
    }//GEN-LAST:event_Socket2StopSendActionPerformed

    private void Socket2StartReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket2StartReceiveActionPerformed

        Socket1StartReceive.setEnabled(false);
        Socket2StartReceive.setEnabled(false);
        Socket3StartReceive.setEnabled(false);
        Socket4StartReceive.setEnabled(false);
        Socket1StopReceive.setEnabled(false);
        Socket2StopReceive.setEnabled(true);
        Socket3StopReceive.setEnabled(false);
        Socket4StopReceive.setEnabled(false);
        
        GlobalVariables.Socket2ReceiveRun = true;
        Socket2Receiver socket2Receiver = new Socket2Receiver();
        socket2Receiver.start();
    }//GEN-LAST:event_Socket2StartReceiveActionPerformed

    private void Socket1StartSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket1StartSendActionPerformed
        Socket1StartSend.setEnabled(false);
        Socket2StartSend.setEnabled(false);
        Socket3StartSend.setEnabled(false);
        Socket4StartSend.setEnabled(false);
        Socket1StopSend.setEnabled(true);   
        
        GlobalVariables.Socket1SendRun = true;
        Socket1Sender socket1Send = new Socket1Sender();
        socket1Send.start();
    }//GEN-LAST:event_Socket1StartSendActionPerformed

    private void Socket1StopSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket1StopSendActionPerformed
        Socket1StartSend.setEnabled(true);
        Socket2StartSend.setEnabled(true);
        Socket3StartSend.setEnabled(true);
        Socket4StartSend.setEnabled(true);
        Socket1StopSend.setEnabled(false);
        
        GlobalVariables.Socket1SendRun = false;
    }//GEN-LAST:event_Socket1StopSendActionPerformed

    private void Socket3StopSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket3StopSendActionPerformed
        Socket1StartSend.setEnabled(true);
        Socket2StartSend.setEnabled(true);
        Socket3StartSend.setEnabled(true);
        Socket4StartSend.setEnabled(true);
        Socket3StopSend.setEnabled(false);
        
        GlobalVariables.Socket3SendRun = false;
    }//GEN-LAST:event_Socket3StopSendActionPerformed

    private void Socket4StopSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket4StopSendActionPerformed
        Socket1StartSend.setEnabled(true);
        Socket2StartSend.setEnabled(true);
        Socket3StartSend.setEnabled(true);
        Socket4StartSend.setEnabled(true);
        Socket4StopSend.setEnabled(false);
        
        GlobalVariables.Socket4SendRun = false;
    }//GEN-LAST:event_Socket4StopSendActionPerformed

    private void Socket3StartSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket3StartSendActionPerformed
        Socket1StartSend.setEnabled(false);
        Socket2StartSend.setEnabled(false);
        Socket3StartSend.setEnabled(false);
        Socket4StartSend.setEnabled(false);
        Socket3StopSend.setEnabled(true);
                
        GlobalVariables.Socket3SendRun = true;
        Socket3Sender socket3Send = new Socket3Sender();
        socket3Send.start();           
    }//GEN-LAST:event_Socket3StartSendActionPerformed

    private void Socket4StartSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket4StartSendActionPerformed
        Socket1StartSend.setEnabled(false);
        Socket2StartSend.setEnabled(false);
        Socket3StartSend.setEnabled(false);
        Socket4StartSend.setEnabled(false);
        Socket4StopSend.setEnabled(true);
        
        GlobalVariables.Socket4SendRun = true;
        Socket4Sender socket4Send = new Socket4Sender();
        socket4Send.start();  
    }//GEN-LAST:event_Socket4StartSendActionPerformed

    private void Socket1StartReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket1StartReceiveActionPerformed
        Socket1StartReceive.setEnabled(false);
        Socket2StartReceive.setEnabled(false);
        Socket3StartReceive.setEnabled(false);
        Socket4StartReceive.setEnabled(false);
        Socket1StopReceive.setEnabled(true);
        
        GlobalVariables.Socket1ReceiveRun = true;
        Socket1Receiver socket1Receiver = new Socket1Receiver();
        socket1Receiver.start();
    }//GEN-LAST:event_Socket1StartReceiveActionPerformed

    private void Socket3StartReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket3StartReceiveActionPerformed
        Socket1StartReceive.setEnabled(false);
        Socket2StartReceive.setEnabled(false);
        Socket3StartReceive.setEnabled(false);
        Socket4StartReceive.setEnabled(false);
        Socket3StopReceive.setEnabled(true);
        
        GlobalVariables.Socket3ReceiveRun = true;
        Socket3Receiver socket3Receiver = new Socket3Receiver();
        socket3Receiver.start();
    }//GEN-LAST:event_Socket3StartReceiveActionPerformed

    private void Socket4StartReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket4StartReceiveActionPerformed
        Socket1StartReceive.setEnabled(false);
        Socket2StartReceive.setEnabled(false);
        Socket3StartReceive.setEnabled(false);
        Socket4StartReceive.setEnabled(false);
        Socket4StopReceive.setEnabled(true);
        
        GlobalVariables.Socket4ReceiveRun = true;
        Socket4Receiver socket4Receiver = new Socket4Receiver();
        socket4Receiver.start();
    }//GEN-LAST:event_Socket4StartReceiveActionPerformed

    private void Socket1StopReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket1StopReceiveActionPerformed
        Socket1StopReceive.setEnabled(false);
        Socket1StartReceive.setEnabled(true);
        Socket2StartReceive.setEnabled(true);
        Socket3StartReceive.setEnabled(true);
        Socket4StartReceive.setEnabled(true);
        
        GlobalVariables.Socket1ReceiveRun = false;
    }//GEN-LAST:event_Socket1StopReceiveActionPerformed

    private void Socket2StopReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket2StopReceiveActionPerformed
        Socket2StopReceive.setEnabled(false);
        Socket1StartReceive.setEnabled(true);
        Socket2StartReceive.setEnabled(true);
        Socket3StartReceive.setEnabled(true);
        Socket4StartReceive.setEnabled(true);
        
        GlobalVariables.Socket2ReceiveRun = false;
    }//GEN-LAST:event_Socket2StopReceiveActionPerformed

    private void Socket3StopReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket3StopReceiveActionPerformed
        Socket3StopReceive.setEnabled(false);
        Socket1StartReceive.setEnabled(true);
        Socket2StartReceive.setEnabled(true);
        Socket3StartReceive.setEnabled(true);
        Socket4StartReceive.setEnabled(true);
        
        GlobalVariables.Socket3ReceiveRun = false;
    }//GEN-LAST:event_Socket3StopReceiveActionPerformed

    private void Socket4StopReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Socket4StopReceiveActionPerformed
        Socket4StopReceive.setEnabled(false);
        Socket1StartReceive.setEnabled(true);
        Socket2StartReceive.setEnabled(true);
        Socket3StartReceive.setEnabled(true);
        Socket4StartReceive.setEnabled(true);
        
        GlobalVariables.Socket4ReceiveRun = false;
    }//GEN-LAST:event_Socket4StopReceiveActionPerformed

    private void portCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_portCaretUpdate
        try{
        GlobalVariables.port = Integer.parseInt(port.getText());
        port.setBackground(Color.getHSBColor(0, 0, 1));
            System.out.println("SET: "+port.getText());
        }
        catch(NumberFormatException ex){
    
            port.setBackground(Color.getHSBColor(0, 1, 1));
            System.out.println("ERROR"+port.getText());
        }
    }//GEN-LAST:event_portCaretUpdate

    private void iPAddressCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_iPAddressCaretUpdate
       GlobalVariables.iPAddress = iPAddress.getText();
    }//GEN-LAST:event_iPAddressCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Socket1StartReceive;
    public static javax.swing.JButton Socket1StartSend;
    public static javax.swing.JButton Socket1StopReceive;
    public static javax.swing.JButton Socket1StopSend;
    public static javax.swing.JButton Socket2StartReceive;
    public static javax.swing.JButton Socket2StartSend;
    public static javax.swing.JButton Socket2StopReceive;
    public static javax.swing.JButton Socket2StopSend;
    public static javax.swing.JButton Socket3StartReceive;
    public static javax.swing.JButton Socket3StartSend;
    public static javax.swing.JButton Socket3StopReceive;
    public static javax.swing.JButton Socket3StopSend;
    public static javax.swing.JButton Socket4StartReceive;
    public static javax.swing.JButton Socket4StartSend;
    public static javax.swing.JButton Socket4StopReceive;
    public static javax.swing.JButton Socket4StopSend;
    private javax.swing.JTextField iPAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField log;
    public static javax.swing.JTextField log2;
    private javax.swing.JTextField port;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        initComponents();
        setVisible(true);
    }
}
